[package]
name = "libxml"
version = "0.2.6"
edition = "2018"
authors = ["Andreas Franzén <andreas@devil.se>", "Deyan Ginev <deyan.ginev@gmail.com>","Jan Frederik Schaefer <j.schaefer@jacobs-university.de>"]
description = "A Rust wrapper for libxml2 - the XML C parser and toolkit developed for the Gnome project"
repository = "https://github.com/KWARC/rust-libxml"
documentation = "http://kwarc.github.io/rust-libxml/libxml/index.html"
readme = "README.md"
license = "MIT"

build = "build.rs"
exclude = [
  "scripts/*"
]

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.2"

[lib]
name = "libxml"
