[package]
name = "rustlibxml"
version = "0.0.1"
authors = ["Jan Frederik Schaefer <j.schaefer@jacobs-university.de>"]
build = "build.rs"

[dependencies]
libc = "~0.1"

[build-dependencies]
gcc = "0.3.21"

[lib]
name = "rustlibxml"

