on: [push, pull_request]

name: CI Windows

jobs:
  test-default-windows:
    name: Windows default
    runs-on: windows-latest
    env: 
      VCPKGRS_DYNAMIC: 1
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_ROOT: C:\vcpkg
    steps:
      - name: Setup vcpkg libxml2 Cache
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: C:\vcpkg
          key: vcpkg-libxml2
      - name: Install libxml2 with vcpkg
        run: |
          vcpkg install libxml2
          vcpkg integrate install
      - uses: actions/checkout@v2
      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
